name: Build and Release

on:
  push:
    branches:
      - main
     paths:
       - desktop/**

jobs:
  build:
    name: Build for ${{ matrix.os }} ${{ matrix.arch }}
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]
        arch: [x64, arm64]
        include:
        - os: windows-latest
          arch: ia32

    outputs:
      release_id: ${{ steps.create_release.outputs.id }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Set up Node 16
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install dependencies
        run: |
          cd desktop
          yarn install
      - name: Make Electron Distributable
        run: |
          cd desktop
          yarn make --arch=${{ matrix.arch }}
      - name: Get Git Hash
        id: git_hash
        run: echo "TAG_NAME=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
        shell: bash
      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          draft: true
          files: |
             desktop/out/make/**/*.exe
             desktop/out/make/**/*.deb
             desktop/out/make/**/*.rpm
          name: Desktop Build ${{ steps.git_hash.outputs.TAG_NAME }}
          tag_name: ${{ steps.git_hash.outputs.TAG_NAME }}

  publish_release:
    name: Publish Release
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Edit Release
        uses: irongut/EditRelease@v1.2.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          id: ${{ needs.build.outputs.release_id }}
          draft: false
